# Site settings
title:          Blog
description:    "Serhat Sönmez - Blog"
timezone:       "Europe/Istanbul"

# Author
author:
  name:         Serhat Sönmez
  url:          http://www.serhatsonmez.com.tr
  email:        iletisim@serhatsonmez.com.tr

# Build settings
markdown:       kramdown

# Assets
sass:
  sass_dir:     _sass
  style:        compressed
picture_path:   "/assets/pictures/"

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5

# Defaults
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post
      author: "Serhat Sönmez"
